# Generated by Django 4.0.3 on 2022-04-18 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomMemebr',
            new_name='RoomMember',
        ),
    ]
